"""
Forensic PDF Export (Legal Bundle)
==================================
Converts PanicResult into a professional, court-ready forensic report.
"""

from __future__ import annotations
from fpdf import FPDF
import time
from datetime import datetime

class ForensicReport(FPDF):
    def header(self):
        # Top Bar
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 25, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 8)
        self.cell(0, 10, "FINGUARD AI AUDITOR — FORENSIC EVIDENCE BUNDLE", ln=True)
        self.ln(10)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Digital Forensics Report | FinGuard AI System", align="C")
        self.set_y(-15)
        self.cell(0, 10, "CONFIDENTIAL — EVIDENTIARY USE ONLY", align="C")

def generate_legal_bundle(result: dict, text: str) -> bytes:
    """
    Creates a formal legal audit PDF.
    """
    pdf = ForensicReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # 1. Case Info
    pdf.set_text_color(51, 65, 85)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Report ID:", 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"FG-{int(time.time())}", 1)
    pdf.ln(7)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Date Generated:", 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), 1)
    pdf.ln(12)

    # 2. Risk Score (Big)
    verdict = result.get("verdict", "UNKNOWN")
    score = result.get("confidence", 0)
    color = (220, 38, 38) if verdict == "SCAM" else (234, 88, 12) if verdict == "SUSPICIOUS" else (22, 101, 52)
    
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*color)
    pdf.cell(0, 12, f"AUDIT VERDICT: {verdict} ({score}% Risk Confidence)", ln=True)
    pdf.ln(5)

    # 3. Reasons
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Primary Risk Indicators", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for reason in result.get("reasons", []):
        pdf.cell(5, 6, "-", 0)
        pdf.multi_cell(0, 6, reason)
    pdf.ln(5)

    # 4. Evidence Heatmap (Simplified for PDF)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Evidence Heatmap", ln=True)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(0, 5, "Below is the audited text with flagged segments highlighted for investigation.")
    pdf.ln(2)

    pdf.set_font("Courier", "", 9)
    pdf.set_text_color(51, 65, 85)
    pdf.set_fill_color(254, 226, 226) # light red
    
    # We display the text and list the matches explicitly for legal clarity
    pdf.multi_cell(0, 5, text[:2000] + ("..." if len(text) > 2000 else ""), border=1)
    pdf.ln(5)

    # 5. Extracted Forensics
    if result.get("extracted_urls") or result.get("extracted_phones"):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, "Digital Forensics Data", ln=True)
        
        for url in result.get("extracted_urls", []):
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"URL Found: {url['url']}", ln=True)
            if "reputation" in url:
                rep = url["reputation"]
                pdf.set_font("Helvetica", "", 8)
                pdf.set_x(15)
                pdf.cell(0, 5, f"Age: {rep.get('age')} | Origin: {rep.get('origin')} | Trust Score: {rep.get('score')}/100", ln=True)
                pdf.set_x(15)
                pdf.cell(0, 5, f"Warning: {rep.get('warning')}", ln=True)

        for phone in result.get("extracted_phones", []):
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"Phone Found: {phone}", ln=True)
        pdf.ln(5)

    # 6. Legal Disclaimer
    pdf.set_y(-40)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    disclaimer = (
        "DISCLAIMER: This report is generated by an Artificial Intelligence system for preliminary evidentiary use. "
        "It does not constitute legal advice. While highly accurate, the system may have false positives. "
        "For bank disputes, please attach this report along with your official statement. "
        "Verified by FinGuard Security Engine v1.0."
    )
    pdf.multi_cell(0, 4, disclaimer, align="C")

    return pdf.output(dest="S").encode("latin-1")
